//go:build !linux

package ebpf

import (
	"fmt"

	"github.com/cilium/ebpf"
)

// This file provides fallback stubs for symbols normally generated by bpf2go.
// It's intended to produce clear errors when the generated files are not present
// (for example on CI or on developer machines that haven't run `go generate`).

type bpfObjects struct {
	Sock4Connect *ebpf.Program
}

func loadBpfObjects(objs *bpfObjects, opts *ebpf.CollectionOptions) error {
	return fmt.Errorf("bpf objects not generated: run 'go generate ./proxy/ebpf' on a Linux machine with clang/libbpf installed")
}

func loadBpf() (*ebpf.CollectionSpec, error) {
	return nil, fmt.Errorf("bpf spec not generated: run 'go generate ./proxy/ebpf' on a Linux machine with clang/libbpf installed")
}

func (o *bpfObjects) Close() {}
