//go:build !linux

package ebpf

import (
	"fmt"

	ciliumebpf "github.com/cilium/ebpf"
)

// This file provides fallback stubs for symbols normally generated by bpf2go.
// It produces clear errors when the generated files are not present
// (for example on CI or developer machines that haven't run `go generate`).

// bpfObjects mirrors the structure that bpf2go generates from redirect.c.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error { return nil }

type bpfPrograms struct {
	Sock4Connect *ciliumebpf.Program
	Sock4Sendmsg *ciliumebpf.Program
	Sock6Connect *ciliumebpf.Program
	Sock6Sendmsg *ciliumebpf.Program
}

type bpfMaps struct {
	TcpOrigDst    *ciliumebpf.Map
	UdpOrigDst    *ciliumebpf.Map
	CidrBypassMap *ciliumebpf.Map
	ConfigMap     *ciliumebpf.Map
}

func loadBpfObjects(_ *bpfObjects, _ *ciliumebpf.CollectionOptions) error {
	return fmt.Errorf("bpf objects not generated: run 'go generate ./proxy/ebpf' on a Linux machine with clang/libbpf installed")
}

func loadBpf() (*ciliumebpf.CollectionSpec, error) {
	return nil, fmt.Errorf("bpf spec not generated: run 'go generate ./proxy/ebpf' on a Linux machine with clang/libbpf installed")
}
