// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux && !android

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfLpmCidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [4]uint8
}

type bpfOriginalDst struct {
	_      structs.HostLayout
	Ip     [4]uint32
	Port   uint32
	Family uint32
}

type bpfTcp4tupleKey struct {
	_          structs.HostLayout
	ClientIp   [4]uint32
	ProxyIp    [4]uint32
	ClientPort uint16
	ProxyPort  uint16
	Family     uint8
	Pad        [3]uint8
}

type bpfUdpOrigKey struct {
	_       structs.HostLayout
	SrcPort uint16
	Family  uint8
	Pad     uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	Sock4Connect  *ebpf.ProgramSpec `ebpf:"sock4_connect"`
	Sock4Sendmsg  *ebpf.ProgramSpec `ebpf:"sock4_sendmsg"`
	Sock6Connect  *ebpf.ProgramSpec `ebpf:"sock6_connect"`
	Sock6Sendmsg  *ebpf.ProgramSpec `ebpf:"sock6_sendmsg"`
	VproxySockops *ebpf.ProgramSpec `ebpf:"vproxy_sockops"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	CidrBypassMap *ebpf.MapSpec `ebpf:"cidr_bypass_map"`
	ConfigMap     *ebpf.MapSpec `ebpf:"config_map"`
	TcpCookieMap  *ebpf.MapSpec `ebpf:"tcp_cookie_map"`
	TcpOrigDst    *ebpf.MapSpec `ebpf:"tcp_orig_dst"`
	UdpOrigDst    *ebpf.MapSpec `ebpf:"udp_orig_dst"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	CidrBypassMap *ebpf.Map `ebpf:"cidr_bypass_map"`
	ConfigMap     *ebpf.Map `ebpf:"config_map"`
	TcpCookieMap  *ebpf.Map `ebpf:"tcp_cookie_map"`
	TcpOrigDst    *ebpf.Map `ebpf:"tcp_orig_dst"`
	UdpOrigDst    *ebpf.Map `ebpf:"udp_orig_dst"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.CidrBypassMap,
		m.ConfigMap,
		m.TcpCookieMap,
		m.TcpOrigDst,
		m.UdpOrigDst,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	Sock4Connect  *ebpf.Program `ebpf:"sock4_connect"`
	Sock4Sendmsg  *ebpf.Program `ebpf:"sock4_sendmsg"`
	Sock6Connect  *ebpf.Program `ebpf:"sock6_connect"`
	Sock6Sendmsg  *ebpf.Program `ebpf:"sock6_sendmsg"`
	VproxySockops *ebpf.Program `ebpf:"vproxy_sockops"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.Sock4Connect,
		p.Sock4Sendmsg,
		p.Sock6Connect,
		p.Sock6Sendmsg,
		p.VproxySockops,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
