// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux && !android

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTc_bpf returns the embedded CollectionSpec for tc_bpf.
func loadTc_bpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tc_bpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tc_bpf: %w", err)
	}

	return spec, err
}

// loadTc_bpfObjects loads tc_bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tc_bpfObjects
//	*tc_bpfPrograms
//	*tc_bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTc_bpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTc_bpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tc_bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_bpfSpecs struct {
	tc_bpfProgramSpecs
	tc_bpfMapSpecs
	tc_bpfVariableSpecs
}

// tc_bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_bpfProgramSpecs struct {
	TcIngress *ebpf.ProgramSpec `ebpf:"tc_ingress"`
}

// tc_bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_bpfMapSpecs struct {
	IpWhitelist  *ebpf.MapSpec `ebpf:"ip_whitelist"`
	MacWhitelist *ebpf.MapSpec `ebpf:"mac_whitelist"`
}

// tc_bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_bpfVariableSpecs struct {
	ProxyMark   *ebpf.VariableSpec `ebpf:"proxy_mark"`
	TproxyPort  *ebpf.VariableSpec `ebpf:"tproxy_port"`
	VerboseMode *ebpf.VariableSpec `ebpf:"verbose_mode"`
}

// tc_bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTc_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_bpfObjects struct {
	tc_bpfPrograms
	tc_bpfMaps
	tc_bpfVariables
}

func (o *tc_bpfObjects) Close() error {
	return _Tc_bpfClose(
		&o.tc_bpfPrograms,
		&o.tc_bpfMaps,
	)
}

// tc_bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTc_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_bpfMaps struct {
	IpWhitelist  *ebpf.Map `ebpf:"ip_whitelist"`
	MacWhitelist *ebpf.Map `ebpf:"mac_whitelist"`
}

func (m *tc_bpfMaps) Close() error {
	return _Tc_bpfClose(
		m.IpWhitelist,
		m.MacWhitelist,
	)
}

// tc_bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTc_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_bpfVariables struct {
	ProxyMark   *ebpf.Variable `ebpf:"proxy_mark"`
	TproxyPort  *ebpf.Variable `ebpf:"tproxy_port"`
	VerboseMode *ebpf.Variable `ebpf:"verbose_mode"`
}

// tc_bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTc_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_bpfPrograms struct {
	TcIngress *ebpf.Program `ebpf:"tc_ingress"`
}

func (p *tc_bpfPrograms) Close() error {
	return _Tc_bpfClose(
		p.TcIngress,
	)
}

func _Tc_bpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_bpf_bpfel.o
var _Tc_bpfBytes []byte
